"""fase4_contenido_rx

Revision ID: 5fbbfc155696
Revises: c1e4f25ccb84
Create Date: 2026-09-07 07:11:09.974005
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '5fbbfc155696'
down_revision: str | None = 'c1e4f25ccb84'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas_terapeuticas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('publicada', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('fichas_tecnicas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('area_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('nombre', sa.String(length=160), nullable=False),
    sa.Column('resumen', sa.String(length=500), nullable=True),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('publicada', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas_terapeuticas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('area_id', 'slug', name='uq_ficha_area_slug')
    )
    op.create_index(op.f('ix_fichas_tecnicas_area_id'), 'fichas_tecnicas', ['area_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fichas_tecnicas_area_id'), table_name='fichas_tecnicas')
    op.drop_table('fichas_tecnicas')
    op.drop_table('areas_terapeuticas')
    # ### end Alembic commands ###
