"""fase5_documentos_partner

Revision ID: 0439bfd6221e
Revises: 5fbbfc155696
Create Date: 2026-09-07 07:24:37.249613
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '0439bfd6221e'
down_revision: str | None = '5fbbfc155696'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documentos_partner', sa.Column('content_type', sa.String(length=100), nullable=False))
    op.add_column('documentos_partner', sa.Column('tamano_bytes', sa.BigInteger(), nullable=False))
    op.add_column('documentos_partner', sa.Column('motivo_rechazo', sa.Text(), nullable=True))
    op.add_column('documentos_partner', sa.Column('revisado_por_id', sa.UUID(), nullable=True))
    op.add_column('documentos_partner', sa.Column('revisado_en', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'documentos_partner', 'usuarios', ['revisado_por_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documentos_partner', type_='foreignkey')
    op.drop_column('documentos_partner', 'revisado_en')
    op.drop_column('documentos_partner', 'revisado_por_id')
    op.drop_column('documentos_partner', 'motivo_rechazo')
    op.drop_column('documentos_partner', 'tamano_bytes')
    op.drop_column('documentos_partner', 'content_type')
    # ### end Alembic commands ###
